### ISSUE TITLE
не работает в mac os через finder

### ISSUE THREAD

**Issue by exls** [yar229/WebDavMailRuCloud#79]
Запускаю через docker-compose:
```
version: '2'
services:
  proxy:
    image: mono
    restart: unless-stopped
    volumes:
      - ./WebDavMailRuCloud_1.5.65:/app
    command: [mono, /app/wdmrc.exe, -p, "80", -h, "http://*"]
    ports:
      - "80:80"
```
Начинает показывать содержимое директорий, но потом помирает и выдает в логах следующее:

```
Threadpool worker]: PROPFIND:http://127.0.0.1/common/:127.0.0.1 - Finished processing (138ms, HTTP result: 404)
[Threadpool worker]: PROPFIND:http://127.0.0.1/common/:127.0.0.1 - Start processing
```

**Comment by yar229** [comment]
Скажите версию MacOS и mono
Не работает именно через Finder? А, скажем, через ForkLift?

И на всякий случай посмотрите, чтобы в настройках облака не стояло запрета параллельных сессий.

**Comment by exls** [comment]
Параллельные сессии не решили проблему. mono latest (Mono JIT compiler version 4.8.0 - официальных хаб https://hub.docker.com/_/mono/). 
OS Yosemite отказывается запускать ForkLift. 
Досадно, давно хотел приручить 100 гб по акции от mail.ru

**Comment by yar229** [comment]
Ни разу не трогал MacOS :)
Поставлю на виртуалку, посмотрю, но вряд ли в ближайшие дни

**Comment by exls** [comment]
Не мучайтесь. Прошу лишь повторить мой опыт с docker-compose. Для этого создайте файл docker-compose.yml с содержимым 
```
version: '2'
services:
  proxy:
    image: mono
    restart: unless-stopped
    volumes:
      - ./WebDavMailRuCloud_1.5.65:/app
    command: [mono, /app/wdmrc.exe, -p, "80", -h, "http://*"]
    ports:
      - "80:80"
```
в эту же директорию распакуйте релиз ./WebDavMailRuCloud_1.5.65 и выполните команду 
`docker-compose up`
или
`docker-compose up -d`
